/** Exact English source copy → Simplified Chinese. English stays the source of
 * truth so switching languages does not alter payroll inputs or calculations. */
export const zhStrings: Record<string, string> = {
  'Cash vacation pay uses CRA’s bonus withholding method in this January 1 full-year simulation. Employer year-to-date payroll settings can produce a different payment.': '这项从 1 月 1 日开始的全年模拟中，年假工资现金发放按 CRA 的奖金预扣方法计算。雇主实际的年内累计工资资料和设置可能使支付金额不同。',
  'Statutory holiday pay is an entered paystub amount, not an automatic entitlement calculation. It applies only to the selected paycheque unless you choose Every paycheque.': '法定节假日工资按你输入的工资单金额计算，不自动判断或计算应享待遇。默认仅计入选中的发薪期，除非你选择“每次发薪”。',
  'Manitoba vacation pay': '曼省年假工资规定',
  'Manitoba statutory holidays': '曼省法定节假日规定',
  'CRA vacation pay and public holidays': 'CRA 年假工资与法定节假日工资',
  'CRA controlled and direct tips': 'CRA 雇主经手与员工直接收取的小费',
  'Full-year forecast of base earnings, recurring extras and the selected-cheque holiday amount. Payroll withholding may differ from your final tax return.': '全年预测包含基本收入、定期额外收入，以及仅计入选中发薪期的节假日工资。工资预扣额可能与最终报税结果不同。',
  'Federal income tax on regular earnings': '常规收入的联邦所得税预扣',
  'Manitoba income tax on regular earnings': '常规收入的曼省所得税预扣',
  'Base annual earnings': '全年基本收入',
  'Annual cash vacation pay': '全年年假工资现金发放',
  'Annual statutory holiday pay': '全年法定节假日工资',
  'Annual controlled tips': '全年雇主经手小费',
  'ESTIMATED BASE SALARY': '估算基本年薪',
  'Base salary per year': '基本年薪',
  'Total gross per pay': '每次税前总收入',
  'Estimated base annual salary': '估算基本年薪',
  'Annual total gross income': '全年税前总收入',
  'Base annual income includes regular pay and overtime, before extra vacation pay, statutory holiday pay or controlled tips.': '基本年薪包含正常工资和加班收入，尚未计入额外的年假工资、法定节假日工资或雇主经手小费。',
  'Regular hours every two weeks': '每两周正常工时',
  'Overtime hours every two weeks': '每两周加班工时',
  'hours / 2 weeks': '小时 / 两周',
  'regular hours every two weeks': '每两周正常工时',
  'overtime hours every two weeks': '每两周加班工时',
  'Vacation pay': '年假工资现金发放',
  'Additional earnings': '额外收入',
  'Optional amounts paid on top of your base salary or hourly earnings.': '在基本年薪或时薪收入之外额外支付的金额，可按需要启用。',
  'Vacation pay paid in cash': '年假工资现金发放',
  'Extra vacation pay on each paycheque': '每次发薪额外支付的年假工资',
  'Use only vacation pay paid as extra cash on each paycheque. Leave this off for accrued vacation or paid leave already included in your salary.': '仅用于随每次发薪额外支付的年假工资。尚未发放的累积年假工资，或已包含在年薪中的带薪休假，请保持关闭。',
  '% of eligible earnings': '收入百分比',
  'Vacation pay amount': '年假工资金额',
  'Quick choice': '快捷选择',
  'or enter your own percentage': '或自行输入百分比',
  'Eligible earnings include regular pay and statutory holiday pay, and exclude overtime.': '计算基数包含正常工资和法定节假日工资，不含加班收入。',
  'Include controlled tips in vacation-pay earnings': '将雇主经手的小费计入年假工资基数',
  'Select this only when your employer includes these tips in its vacation-pay calculation.': '仅在雇主的年假工资计算规则包含这些小费时勾选。',
  'Controlled tips': '雇主经手的小费（Controlled Tips）',
  'Recurring tips paid through your employer': '由雇主通过工资定期发放的小费',
  'Controlled tips per paycheque': '每次发薪的雇主经手小费',
  'Enter recurring employer-controlled tips paid through payroll. Direct tips received from customers are not included.': '填写由雇主统一掌握、通过工资定期发放的小费。顾客直接给你、由你自行掌握的小费不填在这里。',
  'Statutory holiday pay': '法定节假日工资',
  'An actual extra amount from your paystub': '工资单中实际额外支付的金额',
  'Statutory holiday pay amount': '法定节假日工资金额',
  'Apply this amount': '此金额适用于',
  'Selected paycheque only': '仅选中的这次发薪',
  'Every paycheque': '每次发薪',
  'Enter the actual extra amount. Selected paycheque only is the default, so it is not repeated across the year. Choose Every paycheque only for a recurring amount.': '填写实际额外支付的金额。默认仅计入选中的这次发薪，不会全年重复。只有定期支付的金额才选择“每次发薪”。',
  'controlled tips per paycheque': '每次发薪的雇主经手小费',
  'statutory holiday pay': '法定节假日工资',
  'statutory holiday pay scope': '法定节假日工资适用范围',
  'vacation pay': '年假工资',
  'vacation pay mode': '年假工资金额方式',
  'vacation pay percentage (0 to 100)': '年假工资比例（0% 至 100%）',
  'weekly hours (greater than zero for linked salary)': '每周正常工时（联动年薪时须大于零）',
  'Vacation pay is paid out with each cheque, not accrued. Income tax uses CRA’s bonus method with simulated vacation pay received earlier in the year.': '年假工资随每次发薪实际支付，不是尚未发放的累积金额。所得税按 CRA 的奖金方法计算，并模拟年内此前已收到的年假工资。',
  'Earlier earnings and vacation payouts are simulated from the first cheque of the year. Your employer’s actual year-to-date amounts can change withholding.': '从年内第一次发薪开始模拟此前收入和年假工资现金发放。雇主记录的实际年内累计金额可能使预扣额不同。',
  'Vacation payout withholding': '年假工资现金发放的所得税预扣',
  'Calculate take-home': '计算到手工资',
  'Calculation mode': '计算模式',
  'Gross-pay estimate inputs': '反推税前年薪的条件',
  'Set a take-home target, then choose the pay schedule and deductions for this estimate.': '先设置目标到手工资，再选择这次反推使用的发薪安排与扣款。',
  'These settings are separate from your take-home calculation.': '这些条件独立于到手工资计算。',
  'Your gross-pay estimate': '你的税前年薪估算',
  'START WITH YOUR GOAL': '从你的目标开始',
  'Set your target, schedule and deductions, then select Find gross pay.': '设置目标、发薪安排和扣款后，点击“反推税前年薪”。',
  'ESTIMATED GROSS SALARY': '估算税前年薪',
  'Per year': '每年',
  'Target comparison': '目标金额对比',
  'Your take-home calculation has not been changed.': '到手工资计算中的条件保持不变。',
  'Gross-pay estimate found.': '已得出税前年薪估算。',
  'Canada': '加拿大',
  'Pay': '薪资',
  'CALCULATOR': '计算器',
  'Canada Pay Calculator': '加拿大薪资计算器',
  'Canada Pay Calculator home': '加拿大薪资计算器首页',
  'Skip to calculator': '跳到计算器',
  'Private by design': '数据留在你的设备',
  'Add to Home Screen': '添加到主屏幕',
  'How estimates work': '了解计算方式',
  'A new version is ready.': '新版本已准备好。',
  'Update app': '更新应用',
  'MADE FOR YOUR EVERYDAY': '让每次发薪都更清楚',
  'Make sense of your pay.': '看懂你的工资。',
  'Your earnings, deductions, and take-home. Clearly.': '收入、扣款、到手工资，一目了然。',
  'Province': '省份',
  'Province of employment': '工作所在省份',
  'Manitoba': '曼尼托巴省',
  'All amounts in CAD': '所有金额均为加元',
  'Your payroll inputs': '你的工资计算条件',
  'Your income': '你的收入',
  'Choose an amount to edit': '选择要修改的收入金额',
  'Edit annual salary': '修改年薪',
  'Edit hourly wage': '修改时薪',
  'Annual salary': '年薪',
  'Base hourly rate': '基础时薪',
  'Hourly rate': '时薪',
  'CAD / year': '加元 / 年',
  'CAD / hour': '加元 / 小时',
  'CAD / cheque': '加元 / 次发薪',
  'CAD / pay': '加元 / 次发薪',
  'CAD': '加元',
  'hours': '小时',
  'Regular hours per week': '每周正常工时',
  'Include overtime': '计入加班',
  'Overtime hours per week': '每周加班工时',
  'Overtime multiplier': '加班工资倍数',
  '× regular rate': '× 基础时薪',
  'Hours are in addition to regular weekly hours. A multiplier of 1.5 means time and a half.': '加班工时是在每周正常工时之外的时间。1.5 倍表示加班时薪为基础时薪的 1.5 倍。',
  'Edit either amount to update the other. Assumes the same hours each week for 52 paid weeks.': '修改年薪或时薪，另一个金额会同步换算。假设全年 52 周均有工资，且每周工时相同。',
  'Your pay schedule': '你的发薪安排',
  'Pay frequency': '发薪频率',
  'Weekly': '每周一次',
  'Bi-weekly': '每两周一次',
  'Semi-monthly': '每月两次',
  'Monthly': '每月一次',
  'Paycheque in the year': '查看年内第几次发薪',
  'Previous paycheque': '上一次发薪',
  'Next paycheque': '下一次发薪',
  'Once each week: 52 paycheques per year.': '每周发薪一次：全年 52 次。',
  'Every two weeks: 26 paycheques per year. Some months have three.': '每两周发薪一次：全年 26 次，部分月份会发薪三次。',
  'Twice each month: 24 paycheques per year.': '每月发薪两次：全年 24 次，与每两周发薪一次不同。',
  'Once each month: 12 paycheques per year.': '每月发薪一次：全年 12 次。',
  'CPP, CPP2, and EI can change when annual limits are reached. This estimate starts with no earlier earnings on January 1.': '达到年度缴费上限后，CPP、CPP2 和 EI 扣款可能变化。本估算从 1 月 1 日开始，假设没有此前的工资收入。',
  'Pension & other deductions': '养老金与其他扣款',
  'Optional': '可选',
  'Employee deductions reduce take-home pay. Employer contributions are shown separately.': '员工缴款会减少到手工资。雇主缴款会单独列出。',
  'Registered Pension Plan': '注册养老金计划（RPP）',
  'Employee RPP contribution · pre-tax': '员工 RPP 缴款 · 税前扣款',
  'Employer pension match': '雇主养老金配比缴款',
  'Employer savings · separate from your take-home': '雇主为退休储蓄缴款 · 单独列出，不减少到手工资',
  'Payroll RRSP': '工资代扣 RRSP 储蓄',
  'Employee RRSP contribution · pre-tax': '员工 RRSP 储蓄缴款 · 税前扣款',
  'Union dues': '工会会费',
  'Income-tax deductible dues': '计算所得税时可扣除的会费',
  'Health & dental benefits': '医疗与牙科福利',
  'Employee premium · after-tax': '员工承担的保费 · 税后扣款',
  'Other pre-tax deduction': '其他税前扣款',
  'Employer-authorized income-tax deduction': '经雇主认可、可减少所得税预扣的扣款',
  'Other after-tax deduction': '其他税后扣款',
  'Deducted from take-home pay': '从到手工资中扣除',
  'Amount type': '金额方式',
  '% of gross': '税前工资的百分比',
  'Fixed per cheque': '每次发薪固定金额',
  'Registered Pension Plan amount': 'RPP 缴款金额',
  'Employer pension match amount': '雇主配比缴款金额',
  'Payroll RRSP amount': 'RRSP 储蓄缴款金额',
  'Union dues amount': '工会会费金额',
  'Health & dental benefits amount': '医疗与牙科保费金额',
  'Other pre-tax deduction amount': '其他税前扣款金额',
  'Other after-tax deduction amount': '其他税后扣款金额',
  'Pre-tax deductions reduce income-tax withholding, not CPP or EI. Confirm eligibility and contribution limits with your employer.': '这里的税前扣款减少所得税预扣，不减少 CPP 或 EI 的计算工资。请向雇主确认扣款资格与缴款额度。',
  'Start with take-home pay': '从目标到手工资反推',
  'Set a net-pay target to estimate the gross salary you would need, using your current schedule and deductions.': '输入目标到手工资，按当前发薪安排和扣款条件估算所需税前年薪。',
  'Target take-home pay': '目标到手工资',
  'Target period': '目标金额对应的周期',
  'Per paycheque': '每次发薪',
  'Average month': '平均每月',
  'Full year': '全年',
  'Find gross pay': '反推税前年薪',
  'Uses the selected paycheque when that target period is chosen.': '选择“每次发薪”时，目标对应上方选中的年内发薪期。',
  'Uses your current schedule and deductions. Select Find gross pay to update the estimate.': '使用当前发薪安排和扣款条件。点击“反推税前年薪”更新估算。',
  'Finding a gross salary estimate…': '正在估算税前年薪…',
  'Estimate found and applied to your income.': '已找到估算年薪，并填入上方收入栏。',
  'Unable to find an estimate. Check the target and your deductions.': '暂时无法得出估算。请检查目标金额和扣款条件。',
  'Estimated annual gross salary': '估算税前年薪',
  'Target take-home': '目标到手工资',
  'Estimated take-home': '估算到手工资',
  'Inputs saved on this device': '输入条件已保存在此设备',
  'Inputs are available for this session': '输入条件仅在本次使用期间保留',
  'Last valid inputs saved on this device': '此设备保留上次有效的输入条件',
  'Reset inputs': '重置输入',
  'Your pay estimate': '你的工资估算',
  'Check your inputs': '请检查输入',
  'Your estimate will appear when all active amounts are valid.': '所有已启用项目的金额有效后，会显示估算结果。',
  'Enter valid amounts to see your take-home estimate.': '请输入有效金额，查看到手工资估算。',
  'YOUR TAKE-HOME PAY': '你的到手工资',
  'Estimate': '估算',
  'Gross per pay': '每次税前工资',
  'Total deductions': '扣款合计',
  'Where your pay goes': '工资如何分配',
  'Gross pay': '税前工资',
  'Regular earnings': '正常工时收入',
  'Overtime earnings': '加班收入',
  'Income tax': '所得税预扣',
  'Federal income tax': '联邦所得税预扣',
  'Manitoba income tax': '曼省所得税预扣',
  'CPP': 'CPP（加拿大养老金）',
  'CPP2': 'CPP2（养老金第二层附加缴费）',
  'EI': 'EI（就业保险）',
  'Your optional deductions': '你的可选扣款',
  'Employee pension (RPP)': '员工养老金缴款（RPP）',
  'Health & dental': '医疗与牙科保费',
  'Take-home pay': '到手工资',
  'Employer pension': '雇主养老金缴款',
  'Added to your pension separately. Your take-home is unchanged.': '单独计入养老金储蓄，不减少你的到手工资。',
  'THE BIGGER PICTURE': '看看全年',
  'Your year at a glance': '全年收支一览',
  'Average monthly take-home': '平均每月到手工资',
  'Annual take-home divided by 12. The number of paycheques in a month can vary.': '全年到手工资除以 12。不同月份实际发薪次数可能不同。',
  'Annual gross income': '全年税前收入',
  'Annual take-home': '全年到手工资',
  'Gross hourly equivalent': '折算税前时薪',
  'Net hourly equivalent': '折算到手时薪',
  'Hourly equivalents unavailable.': '暂时无法折算时薪。',
  'Enter positive working hours to see hourly equivalents.': '请输入大于零的工时，查看折算时薪。',
  'Enter valid positive working hours.': '请输入有效且大于零的工时。',
  'Annual deductions': '全年扣款',
  'Income tax withheld': '所得税预扣合计',
  'Employee retirement': '员工退休储蓄缴款',
  'Other employee deductions': '员工其他扣款',
  'Beyond take-home': '到手工资之外',
  'Effective deduction rate': '总扣款占比',
  'Includes income tax, statutory contributions, and optional employee deductions.': '包含所得税、法定缴费和员工可选扣款。',
  'Employer pension contribution': '雇主养老金缴款',
  'Separate retirement savings, in addition to your employee contributions.': '雇主额外提供的退休储蓄，与员工自己的缴款分别计算。',
  'A full-year forecast with the same earnings and selections all year. Income tax is payroll withholding and may differ from your final tax return.': '假设全年收入和所选条件不变。这里的所得税是工资预扣额，可能与最终报税结果不同。',
  'Estimate notes': '估算说明',
  'Built to bring clarity to payday.': '让每次发薪都更明白。',
  'Your inputs and calculations stay on this device. No account needed.': '输入和计算留在此设备上，无需账号。',
  'Methodology & reference': '计算方法与参考工资单',
  'An estimate of payroll withholding. Your employer’s TD1 amounts, benefits, year-to-date earnings, and rounding can change your actual pay. Final annual income tax may differ.': '本结果是工资预扣估算。雇主采用的 TD1 申报金额、福利、年内累计收入及四舍五入方式，都会影响实际工资。全年最终所得税可能不同。',
  'On your device · no account needed': '在此设备计算 · 无需账号',
  'Offline · calculations stay on your device': '离线模式 · 仍在此设备计算',
  'On your device · offline setup unavailable': '在此设备计算 · 暂时无法设置离线使用',
  'About the estimate': '关于这项估算',
  'Close methodology': '关闭计算说明',
  'The same payroll rules and reference cases as CanadaPayCalculator for iPhone, available in your browser.': '在浏览器中使用与 CanadaPayCalculator iPhone 应用相同的工资计算规则和参考案例。',
  'Payroll rules': '工资计算规则',
  'Tax year': '税务年度',
  'Rates checked September 30, 2026. CRA’s July update leaves Manitoba’s January payroll rules in place.': '参数于 2026 年 9 月 30 日核对。CRA 的 7 月更新保留曼尼托巴省 1 月采用的工资预扣规则。',
  'Each cheque uses CRA’s annualized withholding formulas, federal and Manitoba brackets, basic personal amounts, the Canada employment amount, and CPP and EI tax credits.': '每次发薪使用 CRA 的年化预扣公式，计入联邦及曼省税阶、基本个人免税额、加拿大就业金额，以及 CPP 和 EI 的税额抵免。',
  'A full year of cheques is calculated in order. CPP, CPP2, and EI change as annual limits are reached. Annual take-home is the sum of those cheques; monthly take-home is that total divided by 12.': '按顺序计算全年每次发薪。达到年度缴费上限后，CPP、CPP2 和 EI 扣款会变化。全年到手工资是所有发薪金额之和；平均每月到手工资是全年合计除以 12。',
  'Assumptions': '计算假设',
  'One employer, regular pensionable and insurable wages, CPP eligibility throughout the year, and basic personal tax claims. Basic personal amounts are adjusted for higher incomes.': '假设只有一个雇主，工资属于正常的 CPP 和 EI 计费收入，全年符合 CPP 缴费条件，并仅申报基本个人税额抵免。较高收入的基本个人金额会按规则调整。',
  'Hourly earnings assume 52 paid weeks. Overtime hours repeat each week. Employee RPP, payroll RRSP, union dues, and authorized pre-tax deductions reduce income-tax withholding; CPP and EI still use gross wages.': '时薪收入按全年 52 个带薪周计算，且每周加班工时相同。员工 RPP、工资代扣 RRSP、工会会费及经认可的税前扣款可减少所得税预扣；CPP 和 EI 仍按税前工资计算。',
  'Health, dental, and other after-tax deductions reduce take-home. Employer pension contributions are separate retirement savings. RRSP and pension room is not checked. Employer matching uses your configured amount; individual plan rules may differ.': '医疗、牙科及其他税后扣款会减少到手工资。雇主养老金缴款单独计入退休储蓄。本应用不核验 RRSP 或养老金缴款额度。雇主配比按你输入的金额计算，实际计划规则可能不同。',
  'Reference paycheque': '参考工资单',
  '$65,000 annual salary in Manitoba, paid semi-monthly: 24 cheques per year, with no optional deductions.': '曼省税前年薪 $65,000，每月发薪两次，全年 24 次，无可选扣款。',
  'The estimate column is calculated afresh using the shared payroll configuration.': '“估算”列每次使用共享工资参数重新计算。',
  'Official sources': '官方资料',
  'Payroll withholding can differ from your final tax assessment. Use CRA’s calculator and your employer’s records when checking an actual payment.': '工资预扣额可能与最终税务评估不同。核对实际工资时，请参考 CRA 计算器和雇主的工资记录。',
  'Privacy & offline use': '隐私与离线使用',
  'Calculations run in your browser. Valid inputs are saved locally on this device. No salary or deduction data is sent to a server. GitHub Pages hosts the static app.': '计算在浏览器内进行，有效输入保存在此设备。工资和扣款数据不会发送到服务器。静态应用由 GitHub Pages 托管。',
  'After your first visit, the app is available offline. Updates appear when you reconnect; you choose when to load them.': '首次在线访问并完成缓存后，可离线使用。重新联网后如有新版本，会提示你自行选择何时更新。',
  'Done': '完成',
  'A little closer to payday.': '把工资计算器放到手边。',
  'Close install guide': '关闭安装指南',
  'Keep Canada Pay on your Home Screen. Free, private, and ready when you are.': '将加拿大薪资计算器添加到主屏幕。免费使用，数据留在设备上，随时可用。',
  'On iPhone or iPad': '在 iPhone 或 iPad 上',
  'Open this site in': '用以下浏览器打开本网站：',
  'Safari': 'Safari',
  'Tap': '轻点',
  'Share': '分享',
  '. If needed, open the': '。如有需要，先打开',
  'Page Menu': '页面菜单',
  'first.': '。',
  'Choose': '选择',
  '. Keep': '。保持',
  'Keep': '保持',
  'Open as Web App': '作为 Web App 打开',
  'enabled if offered, then tap': '开启（如果显示此选项），然后轻点',
  'Add': '添加',
  'If you do not see the option, scroll down in the Share menu or open the link directly in Safari.': '如果没有此选项，可向下滚动分享菜单，或直接在 Safari 中打开链接。',
  'On Android or desktop': '在 Android 或电脑上',
  'Install Canada Pay': '安装加拿大薪资计算器',
  'Use your browser’s': '使用浏览器的',
  'Install app': '安装应用',
  'or': '或',
  'option. In browsers without installation support, bookmark this page.': '选项。如果浏览器不支持安装，可以收藏此页面。',
  'Visit once while online to make the calculator available offline.': '先在线访问一次并完成缓存，之后即可离线使用。',
  'Got it': '知道了',
  'Reset your inputs?': '重置输入条件？',
  'Return to the $65,000 annual salary example and remove all optional contributions.': '恢复到税前年薪 $65,000 的示例，并关闭所有可选缴款。',
  'Cancel': '取消',
  'Supplied reference compared with a fresh estimate': '将提供的参考工资单与本次估算对比',
  'Per cheque': '每次发薪',
  'Reference': '参考工资单',
  'Gross': '税前工资',
  'Take-home': '到手工资',
  'T4127 payroll formulas — January 2026': 'T4127 工资预扣公式 — 2026 年 1 月',
  'T4127 payroll formulas — July 2026': 'T4127 工资预扣公式 — 2026 年 7 月',
  'T4032 Manitoba payroll tables': 'T4032 曼省工资预扣表',
  'CRA payroll source': 'CRA 工资预扣资料',
  'CRA Payroll Deductions Online Calculator': 'CRA 在线工资扣款计算器',
  '(opens in a new tab)': '（在新标签页打开）',
  'Other pre-tax deductions assume employer authorization to reduce income-tax withholding.': '其他税前扣款假设已获雇主认可，可减少所得税预扣。',
  'RRSP contributions assume available contribution room and direct payroll remittance.': 'RRSP 缴款假设你有足够缴款额度，并由雇主直接从工资汇入账户。',
  'Select a pay period within the selected frequency\'s annual schedule.': '请选择当前发薪频率对应的有效年内发薪期。',
  'Optional deductions exceed the pay available after taxes. Reduce the contributions.': '可选扣款超过税后可用工资，请减少缴款金额。',
  'The tax configuration is incomplete or invalid.': '税务参数不完整或无效。',
  'Enter no more than 168 total working hours per week.': '每周正常工时与加班工时合计不能超过 168 小时。',
  'Enter an overtime multiplier from 1 to 10.': '请输入 1 至 10 之间的加班工资倍数。',
  'Enter a positive take-home amount with at most two decimal places.': '请输入大于零的到手工资，最多保留两位小数。',
  'Enter a take-home amount greater than zero.': '请输入大于零的到手工资。',
  'Select a valid take-home period.': '请选择有效的目标到手工资周期。',
  'These deduction percentages are too high for a reliable reverse estimate. Reduce percentage deductions or use the forward calculator.': '这些扣款百分比过高，无法可靠反推年薪。请降低百分比扣款，或直接输入税前年薪计算。',
  'Optional deductions leave no achievable take-home pay within the $100,000,000 annual salary limit.': '在税前年薪上限 $100,000,000 以内，当前可选扣款无法产生可行的到手工资。',
  'This target cannot be reached within one cent using these settings and the annual salary limit. Try a nearby amount or adjust deductions.': '在当前条件和年薪上限内，无法把结果控制在目标金额的 $0.01 误差以内。请尝试相近目标或调整扣款。',
  'annual salary': '税前年薪',
  'hourly earnings': '时薪收入',
  'hourly rate': '时薪',
  'regular hours per week': '每周正常工时',
  'hours per week': '每周工时',
  'overtime hours per week': '每周加班工时',
  'overtime hours': '加班工时',
  'overtime multiplier': '加班工资倍数',
  'overtime multiplier (1 to 10)': '加班工资倍数（1 至 10）',
  'weekly hours (maximum 168)': '每周总工时（最多 168 小时）',
  'annual earnings': '全年收入',
  'income type': '收入类型',
  'pension contribution': '养老金缴款',
  'RRSP contribution': 'RRSP 储蓄缴款',
  'union dues': '工会会费',
  'health benefits': '医疗与牙科保费',
  'other pre-tax deduction': '其他税前扣款',
  'other after-tax deduction': '其他税后扣款',
  'employer pension contribution': '雇主养老金缴款',
  'per year': '每年',
  'per average month': '平均每月',
  '/ year': '/ 年',
  '.': '。',
};


export interface GlossaryEntry {
  /** Stable key also identifies the accessible help button in browser tests. */
  key: string;
  terms: string[];
  title: string;
  description: string;
}

/** Explanations describe what this app displays and its existing assumptions.
 * They do not calculate additional entitlements or investment returns. */
export const glossary: GlossaryEntry[] = [
  {
    key: 'federalTax',
    terms: ['联邦所得税预扣'],
    title: '联邦所得税预扣',
    description: '雇主先从工资中扣下、交给加拿大联邦政府的所得税。本应用按这一期工资推算全年收入，再用税阶和抵免额估算预扣额；最终报税时还会按你的全年实际情况结算。',
  },
  {
    key: 'provincialTax',
    terms: ['曼省所得税预扣'],
    title: '曼尼托巴省所得税预扣',
    description: '从工资中预先扣下的曼省所得税，用于省级公共服务。本应用使用曼省税阶和基本个人金额估算，与联邦所得税一起构成工资单上的所得税预扣。',
  },
  {
    key: 'incomeTax',
    terms: ['所得税预扣', '所得税预扣合计'],
    title: '所得税预扣',
    description: '联邦和曼省所得税预扣的合计。它会减少本次到手工资。全年预扣额是各次发薪的合计，最终报税结果可能因实际收入、税额抵免和其他情况而不同。',
  },
  {
    key: 'cpp2',
    terms: ['CPP2（养老金第二层附加缴费）', 'CPP2'],
    title: 'CPP2：养老金第二层附加缴费',
    description: '较高收入区间额外缴纳的一层加拿大养老金款项。在本应用的年内工资模拟中，累计收入达到相应门槛后才会出现，并有年度上限；未达到门槛时金额为零。',
  },
  {
    key: 'cpp',
    terms: ['CPP（加拿大养老金）', 'CPP'],
    title: 'CPP：加拿大养老金缴费',
    description: '工资中用于加拿大养老金计划的员工缴费，帮助积累未来的公共退休保障。这里的 CPP 行包含基础缴费和第一层附加缴费；本估算假设全年符合缴费条件，并按年度免缴额和上限计算。',
  },
  {
    key: 'ei',
    terms: ['EI（就业保险）', 'EI'],
    title: 'EI：就业保险缴费',
    description: '工资中扣除的就业保险保费，用于支持符合条件时的失业等收入保障。本应用按可保工资估算员工保费，达到年度上限后，后续工资中的 EI 扣款会减少或停止。',
  },
  {
    key: 'employerMatch',
    terms: ['雇主养老金配比缴款', '雇主养老金缴款', '雇主配比缴款金额'],
    title: '雇主养老金缴款',
    description: '雇主额外转入养老金计划的钱，单独计入退休储蓄，不从你的到手工资中扣除。本应用按你填写的税前工资百分比或每次发薪固定金额计算；实际配比条件和上限由雇主计划决定。',
  },
  {
    key: 'pension',
    terms: ['注册养老金计划（RPP）', '员工养老金缴款（RPP）', 'RPP 缴款金额', '员工退休储蓄缴款'],
    title: 'RPP：雇主提供的注册养老金计划',
    description: '通常是通过工作单位参加的退休储蓄计划。员工缴款从工资中扣除，因此到手工资会减少；本应用也将其计入可减少所得税预扣的税前扣款。年度员工退休储蓄包括 RPP 和 RRSP 缴款。',
  },
  {
    key: 'rrsp',
    terms: ['工资代扣 RRSP 储蓄', 'RRSP 储蓄缴款金额', 'RRSP'],
    title: 'RRSP：注册退休储蓄计划',
    description: '用于退休储蓄和投资的注册账户。这里填写通过工资直接转入 RRSP 的缴款，钱会从本次工资扣除，并在本应用中减少所得税预扣。计算的是投入账户的金额，不是投资收益；应用假设缴款额度充足，但不会核验额度。',
  },
  {
    key: 'unionDues',
    terms: ['工会会费', '工会会费金额'],
    title: '工会会费',
    description: '为工会提供员工代表、协商等服务而缴纳的会费。本应用将你填写的会费从工资中扣除，并按可减少所得税预扣的扣款处理。',
  },
  {
    key: 'health',
    terms: ['医疗与牙科福利', '医疗与牙科保费', '医疗与牙科保费金额'],
    title: '员工医疗与牙科保费',
    description: '员工承担的医疗或牙科福利计划费用。本应用把这笔钱作为税后扣款：从到手工资中扣除，不用于减少所得税预扣。具体保费和工资单处理方式应以雇主计划为准。',
  },
  {
    key: 'preTax',
    terms: ['其他税前扣款', '其他税前扣款金额'],
    title: '税前扣款',
    description: '在估算所得税预扣前，从计税工资中扣除的项目。这里的“其他税前扣款”假设已获雇主认可；它减少到手工资和所得税预扣，但不减少本应用用于计算 CPP 或 EI 的工资。',
  },
  {
    key: 'afterTax',
    terms: ['其他税后扣款', '其他税后扣款金额'],
    title: '税后扣款',
    description: '所得税等法定扣款计算后，再从工资中扣除的项目。它会减少到手工资，本应用不会用它减少所得税、CPP 或 EI。',
  },
  {
    key: 'effectiveRate',
    terms: ['总扣款占比', '扣款合计'],
    title: '总扣款占比',
    description: '全年员工扣款合计除以全年税前收入。它包含所得税、CPP、CPP2、EI，以及养老金、RRSP 等可选员工扣款，因此不等同于单纯的所得税税率。雇主额外缴款不计入员工扣款。',
  },
  {
    key: 'gross',
    terms: ['税前工资', '每次税前工资', '全年税前收入', '估算税前年薪', '年薪'],
    title: '税前工资',
    description: '扣除所得税、法定缴费和员工可选扣款之前的收入，包括正常工时收入及已设置的加班收入。年薪是全年税前金额；每次税前工资会按所选发薪频率分配。',
  },
  {
    key: 'net',
    terms: ['到手工资', '目标到手工资', '估算到手工资', '全年到手工资'],
    title: '到手工资',
    description: '税前工资减去所得税、CPP、CPP2、EI 和员工可选扣款后，预计实际收到的钱。雇主养老金缴款另外列出。目标到手工资可用来反推当前条件下的估算税前年薪。',
  },
  {
    key: 'monthly',
    terms: ['平均每月到手工资', '平均每月'],
    title: '平均每月到手工资',
    description: '把全年到手工资合计除以 12 得到的月平均值。每两周发薪时，部分月份有三次发薪，所以实际某月收到的金额可能不同。',
  },
  {
    key: 'annual',
    terms: ['全年收支一览', '全年扣款', '全年'],
    title: '全年预测',
    description: '假设收入、每周工时、发薪频率和扣款条件全年不变，按 1 月至 12 月逐次模拟工资。各期金额相加得到全年结果，不用于预测换工作、停薪或收入变化后的实际全年税额。',
  },
  {
    key: 'workedHours',
    terms: ['折算税前时薪', '折算到手时薪'],
    title: '按实际工作小时折算时薪',
    description: '把全年税前收入或到手工资除以全年实际工作小时数。小时数按“每周正常工时加每周加班工时”乘以 52；加班工资倍数只影响收入，不把一小时加班当成多小时工作。',
  },
  {
    key: 'regularHours',
    terms: ['每周正常工时', '正常工时收入'],
    title: '每周正常工时',
    description: '按基础时薪支付的每周工作时间，加班工时另外填写。本应用假设全年 52 周均有工资，且每周工时相同；用这些小时在年薪和时薪之间换算。',
  },
  {
    key: 'overtime',
    terms: ['每周加班工时', '加班工资倍数', '加班收入', '计入加班'],
    title: '加班工时与工资倍数',
    description: '加班工时是正常工时之外的每周工作时间。加班收入按“基础时薪 × 加班工时 × 倍数”计算，例如 1.5 倍就是基础时薪的 1.5 倍。本应用假设每周加班安排相同。',
  },
  {
    key: 'payFrequency',
    terms: ['发薪频率', '查看年内第几次发薪', '每两周一次', '每月两次'],
    title: '发薪频率与年内发薪期',
    description: '每周一次为全年 52 次，每两周一次为 26 次，每月两次为 24 次，每月一次为 12 次。每两周发薪与每月两次发薪不同。选中的年内期数会影响 CPP、CPP2 和 EI 是否已达到年度上限。',
  },
  {
    key: 'taxYear',
    terms: ['税务年度'],
    title: '税务年度',
    description: '表示本次估算采用哪一年的工资预扣参数。税阶、个人金额和缴费上限会随年度变化；页面显示的年度适用于当前整套估算。',
  },
];
